# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: checkin.js

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: "运行 【机场签到】"
        run: |
          node check_in/glados/checkin_env.js
        env:
          TITLE: ${{ secrets.CHECKIN_TITLE }}
          URL: ${{ secrets.CHECKIN_URL }}
          EMAIL: ${{ secrets.CHECKIN_EMAIL }}
          PASSWORD: ${{ secrets.CHECKIN_PASSWORD }}
